### ISSUE TITLE
Maven repository?

### ISSUE THREAD

**Issue by gciatto-unibo** [GustikS/NeuraLogic#2]
Is this nice library available as via some Maven Repository?

If not, may I suggest to consider using one othe following?
- Maven Central - https://central.sonatype.org/publish/publish-guide/
- GitHub Packages - https://github.com/features/packages
- JitPack - https://jitpack.io/

This would greatly impact the re-usability of you library, IMHO.

**Comment by GustikS** [comment]
Hello, thanks a lot for your interest! 

I was planning to do that, but wanted to create some documentation first so that it's a bit more user-friendly. However, in this direction, we instead started with a whole Python fronted: [https://github.com/LukasZahradnik/PyNeuraLogic](https://github.com/LukasZahradnik/PyNeuraLogic) which should be finished in 3 months and available via pip. Given the prevalence of Python over Java in the ML world, that looked like a more direct usability booster...

However, I might still do at least some documentation for this Java backend and publish it as you suggest, too, so I'll leave this open :)

**Comment by GustikS** [comment]
Hi @gciatto-unibo , so I'm finally happy to close this... after almost a year :D You can now load the library from Maven Central or Github Packages as:

```xml
<dependency>
  <groupId>io.github.gustiks</groupId>
  <artifactId>neuralogic-cli</artifactId>
  <version>0.3.0</version>
</dependency>
```

The documentation is still very sparse, but the Python frontend should mitigate that for the common usage

```
$ pip install neuralogic
```

I hope you'll find it useful!

Best wishes,
Gustav
